import { getDefaultShortcuts, getIsMac } from "@/shared/lib/shortcuts";
import type { SettingsState } from "./types";

export const defaultSettings: SettingsState = {
  editor: {
    vimMode: false,
    fontSize: 14,
    fontFamily: "JetBrains Mono",
    fontId: "",
    tabSize: 2,
    insertSpaces: true,
    wordWrap: false,
    lineNumbers: true,
    autoSave: "onFocusChange",
    autoSaveDelay: 1000,
    formatOnSave: false,
    stickyLines: false,
    inlayHints: false,
  },
  terminal: {
    shell: "",
    fontSize: 13,
    fontFamily: "JetBrains Mono",
    fontId: "",
    aiSuggestions: true,
    scrollback: 10000,
  },
  ai: {
    defaultProvider: "anthropic",
    defaultModel: "",
    inlineCompletion: true,
    completionDebounce: 500,
    terminalSuggestions: true,
    terminalSuggestionProvider: null,
    terminalSuggestionModel: null,
    yoloMode: false,
    showThinking: false,
    showUnavailableProviders: true,
    migrationRevision: 1,
    voiceInput: true,
    voiceEngine: "web-speech",
    providers: {
      openai: { model: "" },
      anthropic: { model: "" },
      ollama: { baseUrl: "http://localhost:11434", model: "" },
      deepseek: { baseUrl: "https://api.deepseek.com", model: "" },
      kimi: { baseUrl: "https://api.kimi.com/coding/v1", model: "" },
      gemini: { baseUrl: "https://generativelanguage.googleapis.com", model: "" },
      openrouter: { baseUrl: "https://openrouter.ai/api/v1", model: "" },
      custom: { baseUrl: "", model: "" },
      copilot: { model: "" },
      grok: { baseUrl: "https://api.x.ai/v1", model: "" },
      cursor: { model: "" },
      opencode: { model: "" },
      hermes: { model: "" },
    },
  },
  theme: "dark-default",
  themeMode: "dark",
  keymap: "default",
  layout: {
    sidebarWidth: 250,
    terminalHeight: "50%",
    chatPanelWidth: 380,
  },
  workspace: {
    recentFolders: [],
    recentFiles: [],
    favoriteFolders: [],
  },
  statusbar: {
    visible: true,
    items: [
      "vimMode",
      "cursor",
      "fileType",
      "encoding",
      "eol",
      "gitBranch",
      "gitSync",
      "problems",
      "aiProvider",
      "theme",
    ],
  },
  mcp: {
    servers: [],
  },
  lsp: {
    enabled: {
      typescript: true,
      javascript: true,
      rust: true,
      python: true,
      go: true,
      java: true,
      c: true,
      cpp: true,
      html: true,
      css: true,
    },
  },
  experimental: {
    lsp: true,
    acp: true,
  },
  agent: {
    enabled: false,
    autoApprove: "never",
    allowedCommands: [],
    useProjectRules: true,
  },
  customThemes: {},
  extensions: {},
  shortcuts: getDefaultShortcuts(getIsMac()),
};
