pub mod code_actions;
pub mod completion;
pub mod definition;
pub mod formatting;
pub mod hover;
pub mod inlay_hints;
pub mod references;
pub mod rename;
pub mod server;
pub mod shared;
pub mod signature_help;
pub mod symbols;
pub mod text_document;

pub use code_actions::normalize_code_actions_response;
pub use completion::normalize_completion_response;
pub use definition::definition_target_from_response;
pub use formatting::normalize_formatting_response;
pub use hover::normalize_hover_response;
pub use inlay_hints::normalize_inlay_hints_response;
pub use references::normalize_references_response;
pub use shared::{location_from_value, normalize_workspace_edit};
pub use signature_help::normalize_signature_help_response;
pub use symbols::{normalize_document_symbols_response, normalize_workspace_symbols_response};
